INSERT INTO time_zone (name, offset_utc, offset_minutes) VALUES
                                                             ('Baker Island', 'UTC-12:00', -720),
                                                             ('Niue', 'UTC-11:00', -660),
                                                             ('Hawaii', 'UTC-10:00', -600),
                                                             ('Marquesas Islands', 'UTC-09:30', -570),
                                                             ('Alaska', 'UTC-09:00', -540),
                                                             ('Pacific Time (US & Canada)', 'UTC-08:00', -480),
                                                             ('Mountain Time (US & Canada)', 'UTC-07:00', -420),
                                                             ('Central Time (US & Canada)', 'UTC-06:00', -360),
                                                             ('Eastern Time (US & Canada)', 'UTC-05:00', -300),
                                                             ('Venezuela', 'UTC-04:30', -270),
                                                             ('Atlantic Time (Canada)', 'UTC-04:00', -240),
                                                             ('Newfoundland', 'UTC-03:30', -210),
                                                             ('Brazil', 'UTC-03:00', -180),
                                                             ('South Georgia', 'UTC-02:00', -120),
                                                             ('Azores', 'UTC-01:00', -60),
                                                             ('UTC', 'UTC+00:00', 0),
                                                             ('Paris', 'UTC+01:00', 60),
                                                             ('Athens', 'UTC+02:00', 120),
                                                             ('Tehran', 'UTC+03:30', 210),
                                                             ('Moscow', 'UTC+03:00', 180),
                                                             ('Dubai', 'UTC+04:00', 240),
                                                             ('Kabul', 'UTC+04:30', 270),
                                                             ('Karachi', 'UTC+05:00', 300),
                                                             ('Mumbai', 'UTC+05:30', 330),
                                                             ('Kathmandu', 'UTC+05:45', 345),
                                                             ('Dhaka', 'UTC+06:00', 360),
                                                             ('Cocos Islands', 'UTC+06:30', 390),
                                                             ('Bangkok', 'UTC+07:00', 420),
                                                             ('Beijing', 'UTC+08:00', 480),
                                                             ('Eucla', 'UTC+08:45', 525),
                                                             ('Tokyo', 'UTC+09:00', 540),
                                                             ('Adelaide', 'UTC+09:30', 570),
                                                             ('Sydney', 'UTC+10:00', 600),
                                                             ('Lord Howe Island', 'UTC+10:30', 630),
                                                             ('Solomon Islands', 'UTC+11:00', 660),
                                                             ('Auckland', 'UTC+12:00', 720),
                                                             ('Chatham Islands', 'UTC+12:45', 765),
                                                             ('Samoa', 'UTC+13:00', 780),
                                                             ('Kiritimati', 'UTC+14:00', 840);
